# Generated by Django 5.1.4 on 2025-01-29 15:51

import django.db.models.deletion
import gallery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('buchcover', models.ImageField(blank=True, db_default='default.png', null=True, upload_to='images/')),
                ('seitenanzahl', models.IntegerField(blank=True, null=True)),
                ('beschreibung', models.TextField(blank=True, default='Geben Sie eine kurze Beschreibung über den Inhalt des Buches an.', null=True)),
                ('erscheinungsdatum', models.PositiveSmallIntegerField(blank=True, null=True, validators=[gallery.models.Book.validate_publication_date])),
                ('sprache', models.CharField(blank=True, choices=[('Englisch', 'English'), ('Deutsch', 'Deutsch'), ('Französisch', 'Français'), ('Spanisch', 'Español'), ('Italienisch', 'Italiano')], max_length=50, null=True)),
                ('kategorie', models.CharField(blank=True, choices=[('Romanze', 'Romanze'), ('Historischer Roman', 'Historischer Roman'), ('Krimi', 'Krimi'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Sachbuch', 'Sachbuch'), ('Biografie', 'Biografie'), ('Sonstige', 'Sonstige')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker', models.CharField(blank=True, choices=[('None', 'None'), ('Geplant', 'Geplant'), ('Begonnen', 'Begonnen'), ('Gelesen', 'Gelesen')], help_text='Geben Sie Ihren Lesestatus zum Buch an.', max_length=50, null=True)),
                ('begonnen', models.DateField(blank=True, help_text='Startdatum des Lesens.', null=True)),
                ('fortschritt', models.IntegerField(blank=True, help_text='Aktuelle Seite.', null=True)),
                ('bewertung', models.CharField(blank=True, max_length=50, null=True)),
                ('inhaltsfokus', models.CharField(blank=True, help_text='Was hat Ihnen inhaltlich am besten gefallen?', max_length=50, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
