# Generated by Django 5.1.4 on 2025-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='buchcover',
            field=models.ImageField(blank=True, db_default='default.png', null=True, upload_to=''),
        ),
    ]
